### ISSUE TITLE
Ananicy failed to start due to AttributeError

### ISSUE THREAD

**Issue by Nightbane112** [Nefelim4ag/Ananicy#105]
Ananicy tries to reference an attribute which no longer exist. This error has occured since commit [116f30b](https://github.com/Nefelim4ag/Ananicy/commit/116f30b946f3fbbc5bf97d71e72bbf61712b0821).

```
 Traceback (most recent call last):
   File "/usr/bin/ananicy", line 716, in <module>
     main(sys.argv)
   File "/usr/bin/ananicy", line 698, in main
     daemon = Ananicy()
   File "/usr/bin/ananicy", line 228, in __init__
     self.run_cmd(["systemd-notify", "--ready"])
 AttributeError: 'Ananicy' object has no attribute 'run_cmd'
```

**Comment by Nightbane112** [comment]
Can confirm commit [d899b94](https://github.com/Nefelim4ag/Ananicy/commit/d899b948173fa0e051a4b8f232bdc0c34f43e4a8) fixed it. Thank you!
