### ISSUE TITLE
Traceback ananicy.service failed PermissionError: [Errno 13]

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#113]
Traceback on recent boot pointing to PermissionError: [Errno 13]. Rules are all defaults from last upgrade.
```
May 28 11:48:50 xmg ananicy[474]: Traceback (most recent call last):
May 28 11:48:50 xmg ananicy[474]:   File "/usr/bin/ananicy", line 726, in <module>
May 28 11:48:50 xmg ananicy[474]:     main(sys.argv)
May 28 11:48:50 xmg ananicy[474]:   File "/usr/bin/ananicy", line 709, in main
May 28 11:48:50 xmg ananicy[474]:     daemon.run()
May 28 11:48:50 xmg ananicy[474]:   File "/usr/bin/ananicy", line 650, in run
May 28 11:48:50 xmg ananicy[474]:     self.proc_map_update()
May 28 11:48:50 xmg ananicy[474]:   File "/usr/bin/ananicy", line 527, in proc_map_update
May 28 11:48:50 xmg ananicy[474]:     for pid in self.proc_get_pids():
May 28 11:48:50 xmg ananicy[474]:   File "/usr/bin/ananicy", line 495, in proc_get_pids
May 28 11:48:50 xmg ananicy[474]:     if not os.path.realpath("/proc/{}/exe".format(pid)):
May 28 11:48:50 xmg ananicy[474]:   File "/usr/lib/python3.6/posixpath.py", line 388, in realpath
May 28 11:48:50 xmg ananicy[474]:     path, ok = _joinrealpath(filename[:0], filename, {})
May 28 11:48:50 xmg ananicy[474]:   File "/usr/lib/python3.6/posixpath.py", line 436, in _joinrealpath
May 28 11:48:50 xmg ananicy[474]:     path, ok = _joinrealpath(path, os.readlink(newpath), seen)
May 28 11:48:50 xmg ananicy[474]: PermissionError: [Errno 13] Permission denied: '/proc/15895/exe'
May 28 11:48:50 xmg systemd[1]: ananicy.service: Main process exited, code=exited, status=1/FAILURE
May 28 11:48:50 xmg systemd[1]: ananicy.service: Failed with result 'exit-code'.
May 28 11:48:50 xmg systemd[1]: ananicy.service: Consumed 782ms CPU time
May 28 11:48:51 xmg systemd[1]: ananicy.service: Service hold-off time over, scheduling restart.
May 28 11:48:51 xmg systemd[1]: ananicy.service: Scheduled restart job, restart counter is at 1.
May 28 11:48:51 xmg systemd[1]: Stopped Ananicy - ANother Auto NICe daemon.
May 28 11:48:51 xmg systemd[1]: ananicy.service: Consumed 782ms CPU time
May 28 11:48:51 xmg systemd[1]: Starting Ananicy - ANother Auto NICe daemon...

```

**Comment by ryanmusante** [comment]
I had incorrectly changed directory permissions. I uninstalled, removed directory and re-installed. User error.
