### ISSUE TITLE
Crash:IndexError: list index out of range

### ISSUE THREAD

**Issue by lindroidux** [Nefelim4ag/Ananicy#157]
[uname -a output:
Linux tsid 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux]

[output of journalctl -aefu  ananicy]
Load rules: /etc/ananicy.d/00-default/imagemagick.rules
Jun 23 14:27:33 tsid ananicy[10828]: Load rules: /etc/ananicy.d/00-default/google-chrome.rules
Jun 23 14:27:33 tsid ananicy[10828]: Traceback (most recent call last):
Jun 23 14:27:33 tsid ananicy[10828]:   File "/usr/bin/ananicy", line 769, in <module>
Jun 23 14:27:33 tsid ananicy[10828]:     main(sys.argv)
Jun 23 14:27:33 tsid ananicy[10828]:   File "/usr/bin/ananicy", line 750, in main
Jun 23 14:27:33 tsid ananicy[10828]:     daemon.run()
Jun 23 14:27:33 tsid ananicy[10828]:   File "/usr/bin/ananicy", line 688, in run
Jun 23 14:27:33 tsid ananicy[10828]:     self.process_tpid(tpid)
Jun 23 14:27:33 tsid ananicy[10828]:   File "/usr/bin/ananicy", line 671, in process_tpid
Jun 23 14:27:33 tsid ananicy[10828]:     rule_name = pe.stat_name
Jun 23 14:27:33 tsid ananicy[10828]:   File "/usr/bin/ananicy", line 74, in stat_name
Jun 23 14:27:33 tsid ananicy[10828]:     return _status_file.readline().split()[1]
Jun 23 14:27:33 tsid ananicy[10828]: IndexError: list index out of range
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Failed with result 'exit-code'.
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Consumed 351ms CPU time.
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Service RestartSec=100ms expired, scheduling restart.
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Scheduled restart job, restart counter is at 6.
Jun 23 14:27:33 tsid systemd[1]: Stopped Ananicy - ANother Auto NICe daemon.
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Consumed 351ms CPU time.
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Start request repeated too quickly.
Jun 23 14:27:33 tsid systemd[1]: ananicy.service: Failed with result 'exit-code'.
Jun 23 14:27:33 tsid systemd[1]: Failed to start Ananicy - ANother Auto NICe daemon.

**Comment by lindroidux** [comment]
Thank u vy much

**Comment by lindroidux** [comment]
Jul 02 19:52:14 tsid ananicy[11050]: Load rules: /etc/ananicy.d/00-default/skype.rules
Jul 02 19:52:14 tsid ananicy[11050]: Load rules: /etc/ananicy.d/00-default/imagemagick.rules
Jul 02 19:52:14 tsid ananicy[11050]: Load rules: /etc/ananicy.d/00-default/google-chrome.rules
Jul 02 19:52:14 tsid ananicy[11050]: Traceback (most recent call last):
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 773, in <module>
Jul 02 19:52:14 tsid ananicy[11050]:     main(sys.argv)
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 754, in main
Jul 02 19:52:14 tsid ananicy[11050]:     daemon.run()
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 692, in run
Jul 02 19:52:14 tsid ananicy[11050]:     self.process_tpid(tpid)
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 675, in process_tpid
Jul 02 19:52:14 tsid ananicy[11050]:     rule_name = pe.stat_name
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 77, in stat_name
Jul 02 19:52:14 tsid ananicy[11050]:     return line_list[1]
Jul 02 19:52:14 tsid ananicy[11050]: IndexError: list index out of range
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Main process exited, code=exited, status=1/FAILURE
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Failed with result 'exit-code'.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Consumed 353ms CPU time.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Service RestartSec=100ms expired, scheduling restart.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Scheduled restart job, restart counter is at 7.
Jul 02 19:52:14 tsid systemd[1]: Stopped Ananicy - ANother Auto NICe daemon.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Consumed 353ms CPU time.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Start request repeated too quickly.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Failed with result 'exit-code'.
Jul 02 19:52:14 tsid systemd[1]: Failed to start Ananicy - ANother Auto NICe daemon.
