### ISSUE TITLE
More "ananicy dump proc" Issues

### ISSUE THREAD

**Issue by nealevans** [Nefelim4ag/Ananicy#427]
I see the run ananicy dump proc:

```
$ sudo ananicy dump proc
Traceback (most recent call last):
  File "/usr/bin/ananicy", line 841, in <module>
    main(sys.argv)
  File "/usr/bin/ananicy", line 833, in main
    daemon.dump_proc()
  File "/usr/bin/ananicy", line 757, in dump_proc
    print(json.dumps(proc_dict, indent=4), flush=True)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.9/json/encoder.py", line 376, in _iterencode_dict
    raise TypeError(f'keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not tuple
 following when I run ananicy dump proc:
```

Python version? (There's an xkcd for this).

Thank you,

-Neal

**Comment by Vistaus** [comment]
Same here, but with Python 3.7.

**Comment by gardotd426** [comment]
Same, but with Python 3.9 (Arch Linux).

**Comment by IgorPereira1997** [comment]
Same here, Python 3.10 in Arch Linux

**Comment by meisme-dev** [comment]
Same here

**Comment by CygnusTerminal** [comment]
Same here (arch, python 3.10)
